// Mock data for multi-tenant ATS
// In production, this would come from Supabase filtered by company

export const mockJobs = [
  {
    id: 'job-1',
    companySlug: 'demo-company',
    title: 'Senior Software Engineer',
    department: 'Engineering',
    location: 'San Francisco, CA',
    type: 'Full-time',
    salary: '$150k - $200k',
    applicants: 24,
    posted: '3 days ago',
    status: 'Active',
    description: 'Looking for an experienced software engineer to join our core platform team.',
    fullDescription: `We're seeking a Senior Software Engineer to join our core platform team and help build the future of enterprise software. You'll work on challenging problems at scale, building features that directly impact thousands of businesses.`,
    responsibilities: [
      'Design and implement scalable backend services using Node.js and TypeScript',
      'Build responsive frontend features with React and Next.js',
      'Collaborate with product and design teams to ship high-quality features',
      'Mentor junior engineers and contribute to technical decisions',
      'Participate in code reviews and maintain high code quality standards',
    ],
    requirements: [
      '5+ years of professional software engineering experience',
      'Strong proficiency in JavaScript/TypeScript, React, and Node.js',
      'Experience building and scaling distributed systems',
      'Excellent communication and collaboration skills',
      'BS in Computer Science or equivalent experience',
    ],
    niceToHave: [
      'Experience with AI/ML technologies',
      'Previous experience at a high-growth startup',
      'Open source contributions',
      'Experience with AWS or other cloud platforms',
    ],
  },
  {
    id: 'job-2',
    companySlug: 'demo-company',
    title: 'Product Manager',
    department: 'Product',
    location: 'Remote',
    type: 'Full-time',
    salary: '$130k - $180k',
    applicants: 18,
    posted: '1 week ago',
    status: 'Active',
    description: 'Seeking a strategic product manager to lead our analytics products.',
    fullDescription: `We're looking for a strategic Product Manager to lead our analytics product line. You'll own the product vision and roadmap, working closely with engineering, design, and customers.`,
    responsibilities: [
      'Define and execute product strategy for analytics features',
      'Conduct user research and gather customer feedback',
      'Write detailed product specifications and user stories',
      'Work closely with engineering and design to ship features',
      'Analyze product metrics and drive data-informed decisions',
    ],
    requirements: [
      '3+ years of product management experience in B2B SaaS',
      'Strong analytical skills and data-driven mindset',
      'Excellent communication and stakeholder management',
      'Experience with analytics or data products',
      'Technical background or engineering degree preferred',
    ],
    niceToHave: [
      'MBA from top business school',
      'Experience in HR tech or recruiting space',
      'SQL proficiency',
      'Experience with AI-powered products',
    ],
  },
  {
    id: 'job-3',
    companySlug: 'demo-company',
    title: 'Senior Product Designer',
    department: 'Design',
    location: 'New York, NY',
    type: 'Full-time',
    salary: '$120k - $160k',
    applicants: 31,
    posted: '2 weeks ago',
    status: 'Active',
    description: 'Join our design team to create beautiful and intuitive user experiences.',
    fullDescription: `We're seeking a Senior Product Designer to create beautiful, intuitive experiences for our enterprise customers. You'll own the end-to-end design process for key product areas.`,
    responsibilities: [
      'Design end-to-end user experiences for new product features',
      'Create high-fidelity mockups and interactive prototypes',
      'Conduct user research and usability testing',
      'Collaborate with product and engineering teams',
      'Contribute to and maintain our design system',
    ],
    requirements: [
      '4+ years of product design experience',
      'Strong portfolio demonstrating UX and visual design skills',
      'Proficiency in Figma and modern design tools',
      'Experience with design systems',
      'Excellent communication and presentation skills',
    ],
    niceToHave: [
      'Experience in B2B SaaS or enterprise products',
      'Front-end development skills (HTML/CSS/React)',
      'Animation and motion design experience',
      'Experience mentoring junior designers',
    ],
  },
  // TechStart Inc jobs (different company - should NOT show in Your Company dashboard)
  {
    id: 'job-4',
    companySlug: 'techstart',
    title: 'Machine Learning Engineer',
    department: 'AI/ML',
    location: 'Remote',
    type: 'Full-time',
    salary: '$160k - $220k',
    applicants: 12,
    posted: '1 day ago',
    status: 'Active',
    description: 'Build cutting-edge ML models for our AI platform.',
    fullDescription: `Join our AI team to build state-of-the-art machine learning models.`,
    responsibilities: [],
    requirements: [],
    niceToHave: [],
  },
];

// Companies using Better ATS
export const mockCompanies = [
  {
    slug: 'demo-company',
    name: 'Demo Company',
    description: 'Building the future of enterprise software',
    website: 'https://demo-company.com',
  },
  {
    slug: 'techstart',
    name: 'TechStart Inc',
    description: 'Innovative AI solutions for modern businesses',
    website: 'https://techstart.io',
  },
];

// Pipeline stages that candidates move through
export const PIPELINE_STAGES = [
  { id: 'applied', name: 'New Applicants', color: 'slate' },
  { id: 'screening', name: 'Screening', color: 'blue' },
  { id: 'interview', name: 'Interview', color: 'purple' },
  { id: 'offer', name: 'Offer', color: 'green' },
  { id: 'hired', name: 'Hired', color: 'emerald' },
  { id: 'rejected', name: 'Rejected', color: 'red' },
];

export const mockCandidates = [
  {
    id: 'candidate-1',
    companySlug: 'demo-company',
    jobId: 'job-1',
    name: 'Sarah Chen',
    email: 'sarah.chen@email.com',
    linkedin: 'linkedin.com/in/sarahchen',
    appliedDate: '2 days ago',
    appliedDateTimestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    aiScore: 94,
    stage: 'interview', // Pipeline stage
    jobTitle: 'Senior Software Engineer',
    matchReasons: [
      'Strong match: 7 years of experience with React and TypeScript',
      'Previously built distributed systems at scale (10M+ users)',
      'Led engineering team of 8 developers',
      'Open source contributions to popular Node.js libraries',
    ],
    skillMatch: ['React', 'Node.js', 'TypeScript', 'Microservices', 'AWS'],
    experience: '7 years',
    currentRole: 'Senior Engineer at Tech Corp',
    education: 'BS Computer Science, Stanford University',
  },
  {
    id: 'candidate-2',
    companySlug: 'demo-company',
    jobId: 'job-1',
    name: 'Michael Rodriguez',
    email: 'michael.r@email.com',
    linkedin: 'linkedin.com/in/mrodriguez',
    appliedDate: '3 days ago',
    appliedDateTimestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    aiScore: 89,
    stage: 'screening',
    jobTitle: 'Senior Software Engineer',
    matchReasons: [
      'Strong technical background: 6 years full-stack development',
      'Experience with React, Node.js, and TypeScript',
      'Built microservices architecture at previous company',
      'Strong system design skills demonstrated in projects',
    ],
    skillMatch: ['React', 'Node.js', 'TypeScript', 'Docker', 'PostgreSQL'],
    experience: '6 years',
    currentRole: 'Software Engineer at StartupXYZ',
    education: 'MS Computer Science, MIT',
  },
  {
    id: 'candidate-3',
    companySlug: 'demo-company',
    jobId: 'job-1',
    name: 'Emily Watson',
    email: 'e.watson@email.com',
    linkedin: 'linkedin.com/in/emilywatson',
    appliedDate: '5 days ago',
    appliedDateTimestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    aiScore: 86,
    stage: 'applied',
    jobTitle: 'Senior Software Engineer',
    matchReasons: [
      'Relevant experience: 5 years in backend development',
      'Strong Node.js and TypeScript skills',
      'Experience with cloud infrastructure (AWS, GCP)',
      'Good communication skills based on writing samples',
    ],
    skillMatch: ['Node.js', 'TypeScript', 'AWS', 'MongoDB', 'Redis'],
    experience: '5 years',
    currentRole: 'Backend Engineer at CloudTech',
    education: 'BS Software Engineering, UC Berkeley',
  },
  {
    id: 'candidate-4',
    companySlug: 'demo-company',
    jobId: 'job-1',
    name: 'David Kim',
    email: 'david.kim@email.com',
    linkedin: 'linkedin.com/in/davidkim',
    appliedDate: '1 week ago',
    appliedDateTimestamp: Date.now() - 7 * 24 * 60 * 60 * 1000,
    aiScore: 82,
    stage: 'applied',
    jobTitle: 'Senior Software Engineer',
    matchReasons: [
      'Solid technical skills: 5 years of experience',
      'Experience with React and modern JavaScript',
      'Built scalable APIs serving millions of requests',
      'Active contributor to tech community',
    ],
    skillMatch: ['React', 'JavaScript', 'Python', 'Docker', 'Kubernetes'],
    experience: '5 years',
    currentRole: 'Full Stack Developer at DataCo',
    education: 'BS Computer Engineering, Georgia Tech',
  },
  {
    id: 'candidate-5',
    companySlug: 'demo-company',
    jobId: 'job-2',
    name: 'Jessica Park',
    email: 'jessica.park@email.com',
    linkedin: 'linkedin.com/in/jessicapark',
    appliedDate: '1 day ago',
    appliedDateTimestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
    aiScore: 91,
    stage: 'offer',
    jobTitle: 'Product Manager',
    matchReasons: [
      'Strong PM background: 5 years in B2B SaaS',
      'Led analytics product line generating $20M ARR',
      'Data-driven approach with strong SQL and analytics skills',
      'Excellent stakeholder management experience',
    ],
    skillMatch: ['Product Strategy', 'B2B SaaS', 'Analytics', 'SQL', 'A/B Testing'],
    experience: '5 years',
    currentRole: 'Senior Product Manager at Analytics Inc',
    education: 'MBA, Harvard Business School',
  },
  {
    id: 'candidate-6',
    companySlug: 'demo-company',
    jobId: 'job-2',
    name: 'Alex Thompson',
    email: 'alex.t@email.com',
    linkedin: 'linkedin.com/in/alexthompson',
    appliedDate: '4 days ago',
    appliedDateTimestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    aiScore: 85,
    stage: 'applied',
    jobTitle: 'Product Manager',
    matchReasons: [
      'Relevant experience: 4 years in product management',
      'Built data products from 0 to 1',
      'Strong analytical background with engineering degree',
      'User research and customer interview experience',
    ],
    skillMatch: ['Product Management', 'Data Products', 'User Research', 'Roadmapping'],
    experience: '4 years',
    currentRole: 'Product Manager at SaaS Startup',
    education: 'BS Computer Science, Carnegie Mellon',
  },
  {
    id: 'candidate-7',
    companySlug: 'demo-company',
    jobId: 'job-3',
    name: 'Olivia Martinez',
    email: 'olivia.m@email.com',
    linkedin: 'linkedin.com/in/oliviamartinez',
    appliedDate: '2 days ago',
    appliedDateTimestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    aiScore: 93,
    stage: 'interview',
    jobTitle: 'Senior Product Designer',
    matchReasons: [
      'Exceptional portfolio: 6 years of product design',
      'Led design systems for enterprise SaaS products',
      'Strong UX research skills with proven impact',
      'Experience mentoring junior designers',
    ],
    skillMatch: ['Figma', 'Design Systems', 'UX Research', 'Prototyping', 'User Testing'],
    experience: '6 years',
    currentRole: 'Lead Product Designer at DesignCo',
    education: 'BFA Interaction Design, RISD',
  },
  {
    id: 'candidate-8',
    companySlug: 'demo-company',
    jobId: 'job-3',
    name: 'Chris Anderson',
    email: 'chris.a@email.com',
    linkedin: 'linkedin.com/in/chrisanderson',
    appliedDate: '5 days ago',
    appliedDateTimestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    aiScore: 88,
    stage: 'applied',
    jobTitle: 'Senior Product Designer',
    matchReasons: [
      'Strong design skills: 5 years of experience',
      'Built and maintained design systems at scale',
      'Proficient in Figma with component library expertise',
      'Cross-functional collaboration experience',
    ],
    skillMatch: ['Figma', 'UI/UX Design', 'Design Systems', 'Wireframing'],
    experience: '5 years',
    currentRole: 'Senior Product Designer at CreativeApp',
    education: 'BS Graphic Design, Parsons',
  },
];
